export interface IVDrip {
  name: string
  slug: string
  tagline: string
  description: string
  benefits: string[]
  price: string
  duration: string
  image: string
  targetAudience: string
}

export const ivDripsData: IVDrip[] = [
  {
    name: "Weight Loss - Metabolic Burn IV Drips",
    slug: "weight-loss-metabolic-burn-drip",
    tagline: "Boost fat metabolism",
    description:
      "Specially formulated to support your weight loss journey with essential nutrients that boost metabolism and energy levels.",
    benefits: [
      "Boosts fat metabolism",
      "Supports steady energy during dieting",
      "Replenishes key vitamins & hydration",
    ],
    price: "1550",
    duration: "60-75 min",
    image: "/images/iv-treatments/weight-loss-metabolic-burn.jpg",
    targetAudience: "Adults on supervised weight-loss plans; low-energy individuals; metabolic support clients.",
  },
  {
    name: "Energy Boost - Performance IV Drips",
    slug: "energy-boost-performance-drip",
    tagline: "Elevate natural energy",
    description:
      "Designed to combat fatigue and restore your natural energy levels with a powerful blend of B vitamins and electrolytes.",
    benefits: ["Elevates natural energy", "Reduces fatigue", "Restores electrolytes and hydration"],
    price: "1550",
    duration: "30-45 min",
    image: "/images/iv-treatments/energy-boost-performance.jpg",
    targetAudience: "Busy professionals, shift workers, students, recreational athletes.",
  },
  {
    name: "Skin Freshness - Glow IV Drips",
    slug: "skin-freshness-glow-drip",
    tagline: "Glow from within",
    description:
      "Achieve radiant, youthful skin with our glow-enhancing IV therapy packed with antioxidants and collagen boosters.",
    benefits: ["Promotes collagen production", "Enhances skin radiance", "Fights oxidative stress"],
    price: "1650",
    duration: "45-60 min",
    image: "/images/iv-treatments/skin-freshness-glow.jpg",
    targetAudience: "Clients wanting glowing skin; travelers; individuals exposed to sun/pollution.",
  },
  {
    name: "Bariatric Surgery IV Drips",
    slug: "bariatric-surgery-drip",
    tagline: "Post-surgery recovery",
    description:
      "Essential nutrient support for patients recovering from bariatric surgery, helping restore energy and promote healing.",
    benefits: ["Replenishes nutrients after surgery", "Supports healing & recovery", "Restores energy and hydration"],
    price: "1400",
    duration: "45-60 min",
    image: "/images/iv-treatments/bariatric-surgery-support.jpg",
    targetAudience: "Post-bariatric patients under clinical follow-up.",
  },
  {
    name: "Diabetic Support IV Drips",
    slug: "diabetic-support-drip",
    tagline: "Balanced wellness support",
    description:
      "Specially designed to support diabetic patients with nerve health, antioxidant protection, and electrolyte balance.",
    benefits: ["Supports nerve health", "Provides antioxidant protection", "Balances electrolytes"],
    price: "1550",
    duration: "45-60 min",
    image: "/images/iv-treatments/diabetic-support.jpg",
    targetAudience: "Adults with diabetes or insulin resistance under medical supervision.",
  },
  {
    name: "Sexual Performance - Vitality IV Drips",
    slug: "sexual-performance-vitality-drip",
    tagline: "Enhanced vitality",
    description:
      "Boost your vitality and wellness with nutrients that support hormonal balance and reproductive health.",
    benefits: ["Supports hormonal balance", "Enhances circulation & energy", "Boosts reproductive wellness"],
    price: "1550",
    duration: "45-60 min",
    image: "/images/iv-treatments/sexual-performance-vitality.jpg",
    targetAudience: "Adult men with performance decline; couples optimizing fertility.",
  },
  {
    name: "Chronic Fatigue IV Drips",
    slug: "chronic-fatigue-drip",
    tagline: "Long-term energy support",
    description:
      "Combat persistent fatigue with a comprehensive blend of vitamins and nutrients designed for sustained energy.",
    benefits: ["Supports long-term energy", "Replenishes essential nutrients", "Helps reduce persistent fatigue"],
    price: "1400",
    duration: "45-60 min",
    image: "/images/iv-treatments/chronic-fatigue.jpg",
    targetAudience: "Individuals with persistent fatigue under medical evaluation.",
  },
  {
    name: "Diet & Detox IV Drips",
    slug: "diet-detox-drip",
    tagline: "Cleanse and refresh",
    description:
      "Support your body's natural detoxification processes while maintaining optimal hydration and vitality.",
    benefits: ["Supports liver detox pathways", "Helps reduce toxin buildup", "Enhances hydration & vitality"],
    price: "1400",
    duration: "45-60 min",
    image: "/images/iv-treatments/diet-detox.jpg",
    targetAudience: "Clients on detox programs or exposed to lifestyle toxins.",
  },
  {
    name: "Fertility - Repro Boost IV Drips",
    slug: "fertility-repro-boost-drip",
    tagline: "Fertility support",
    description: "Essential nutrients to support reproductive wellness and prepare your body for conception.",
    benefits: [
      "Supports reproductive wellness",
      "Provides essential fertility nutrients",
      "Helps protect cells from oxidative stress",
    ],
    price: "1400",
    duration: "45-60 min",
    image: "/images/iv-treatments/fertility-repro-boost.jpg",
    targetAudience: "Men and women preparing for pregnancy; fertility optimization clients.",
  },
  {
    name: "Athletic - Recovery IV Drips",
    slug: "athletic-recovery-drip",
    tagline: "Peak performance recovery",
    description: "Accelerate muscle recovery and restore performance levels after intense physical activity.",
    benefits: ["Speeds muscle recovery", "Restores electrolytes", "Enhances performance & stamina"],
    price: "1400",
    duration: "45-60 min",
    image: "/images/iv-treatments/athletic-recovery.jpg",
    targetAudience: "Athletes, gym-goers, labor-intensive workers.",
  },
  {
    name: "Hair Growth IV Drips",
    slug: "hair-growth-drip",
    tagline: "Nourish your hair",
    description: "Promote healthy hair growth with nutrients that nourish follicles and support keratin production.",
    benefits: ["Nourishes hair follicles", "Supports keratin production", "Helps reduce hair thinning"],
    price: "1400",
    duration: "45-60 min",
    image: "/images/iv-treatments/hair-growth.jpg",
    targetAudience: "Clients with hair thinning due to stress, postpartum, or nutrient deficiencies.",
  },
  {
    name: "Depression Support IV Drips",
    slug: "depression-support-drip",
    tagline: "Mood support",
    description:
      "Nutritional support for mental wellness, helping to reduce fatigue and promote nervous system balance.",
    benefits: ["Supports mood-related nutrients", "Helps reduce fatigue", "Promotes nervous-system balance"],
    price: "1400",
    duration: "45-60 min",
    image: "/images/iv-treatments/depression-support.jpg",
    targetAudience: "Adults with low mood or burnout (adjunct support only).",
  },
  {
    name: "Motherhood - Postnatal IV Drips",
    slug: "motherhood-postnatal-drip",
    tagline: "Postnatal recovery",
    description: "Restore nutrient levels and support recovery for new mothers during the postpartum period.",
    benefits: ["Restores nutrient levels", "Supports energy postpartum", "Aids recovery and immune balance"],
    price: "1650",
    duration: "45-60 min",
    image: "/images/iv-treatments/motherhood-postnatal.jpg",
    targetAudience: "Postpartum women needing nutritional replenishment.",
  },
  {
    name: "Immune - Defense IV Drips",
    slug: "immune-defense-drip",
    tagline: "Strengthen your immunity",
    description: "Boost your immune system with a powerful combination of vitamins and antioxidants.",
    benefits: ["Strengthens immune response", "Provides antioxidant protection", "Supports hydration during illness"],
    price: "1400",
    duration: "45-60 min",
    image: "/images/iv-treatments/immune-defense.jpg",
    targetAudience: "People prone to frequent infections or high stress.",
  },
  {
    name: "Jet Lag - Reset IV Drips",
    slug: "jet-lag-reset-drip",
    tagline: "Travel recovery",
    description: "Quickly recover from travel fatigue and jet lag with rehydration and energy-boosting nutrients.",
    benefits: ["Rehydrates after flights", "Supports energy & alertness", "Helps reduce travel fatigue"],
    price: "1300",
    duration: "30-45 min",
    image: "/images/iv-treatments/jet-lag-reset.jpg",
    targetAudience: "Frequent travelers, flight crews, business professionals.",
  },
  {
    name: "Anti-Aging - Renewal IV Drips",
    slug: "anti-aging-renewal-drip",
    tagline: "Cellular renewal",
    description: "Turn back the clock with antioxidants and nutrients that support collagen and cellular health.",
    benefits: ["Supports collagen & skin health", "Provides strong antioxidant support", "Boosts cellular energy"],
    price: "1300",
    duration: "45-60 min",
    image: "/images/iv-treatments/anti-aging-renewal.jpg",
    targetAudience: "Adults seeking longevity, collagen support, and vitality.",
  },
  {
    name: "Anti-Stress - Adrenal IV Drips",
    slug: "anti-stress-adrenal-drip",
    tagline: "Stress relief",
    description: "Support your adrenal health and reduce stress fatigue with calming, restorative nutrients.",
    benefits: ["Helps reduce stress fatigue", "Supports mental clarity", "Nourishes nervous-system balance"],
    price: "1300",
    duration: "45-60 min",
    image: "/images/iv-treatments/anti-stress-adrenal.jpg",
    targetAudience: "High-pressure professionals, caregivers, students.",
  },
  {
    name: "Cold & Flu - Immune Rescue IV Drips",
    slug: "cold-flu-immune-rescue-drip",
    tagline: "Rapid immune support",
    description: "Fast-acting immune support to help you fight cold and flu symptoms and speed up recovery.",
    benefits: ["Strengthens immune defense", "Helps speed up recovery", "Supports hydration when sick"],
    price: "1400",
    duration: "45-60 min",
    image: "/images/iv-treatments/cold-flu-immune-rescue.jpg",
    targetAudience: "Clients recovering from flu, frequent travelers, exposed workers.",
  },
  {
    name: "Migraine - Neuro Calm IV Drips",
    slug: "migraine-neuro-calm-drip",
    tagline: "Headache relief",
    description: "Relief-focused nutrients that support relaxation and help reduce migraine triggers.",
    benefits: [
      "Supports relaxation of blood vessels",
      "Helps reduce headache triggers",
      "Rehydrates and replenishes nutrients",
    ],
    price: "1300",
    duration: "45-60 min",
    image: "/images/iv-treatments/migraine-neuro-calm.jpg",
    targetAudience: "Adults with migraines under neurologist care.",
  },
  {
    name: "Dementia - Cognitive Support IV Drips",
    slug: "dementia-cognitive-support-drip",
    tagline: "Brain health support",
    description: "Nutrients that support cognitive function, memory, and overall brain health.",
    benefits: ["Supports memory-related nutrients", "Provides antioxidant brain protection", "Aids mental clarity"],
    price: "1300",
    duration: "45-60 min",
    image: "/images/iv-treatments/dementia-cognitive-support.jpg",
    targetAudience: "Older adults with memory concerns; cognitive support patients.",
  },
  {
    name: "Hangover - Recovery IV Drips",
    slug: "hangover-recovery-drip",
    tagline: "Rapid rehydration",
    description: "Quick relief from hangover symptoms with rapid rehydration and detox support.",
    benefits: ["Rapidly rehydrates", "Supports liver detox", "Reduces fatigue and nausea"],
    price: "1300",
    duration: "30-45 min",
    image: "/images/iv-treatments/hangover-recovery.jpg",
    targetAudience: "Adults with dehydration or nausea after alcohol intake.",
  },
  {
    name: "Hydration IV Drips",
    slug: "hydration-drip",
    tagline: "Essential hydration",
    description: "Pure hydration therapy to restore fluid balance and support physical performance.",
    benefits: ["Restores electrolytes", "Improves hydration quickly", "Supports physical performance"],
    price: "1300",
    duration: "30-45 min",
    image: "/images/iv-treatments/hydration-drip.jpg",
    targetAudience: "Athletes, dehydrated individuals, travelers.",
  },
  {
    name: "Post Surgery - Healing IV Drips",
    slug: "post-surgery-healing-drip",
    tagline: "Surgery recovery",
    description: "Support your body's healing process after surgery with essential nutrients and hydration.",
    benefits: ["Supports tissue repair", "Aids immune function", "Restores hydration & nutrients"],
    price: "1200",
    duration: "45-60 min",
    image: "/images/iv-treatments/post-surgery-healing.jpg",
    targetAudience: "Post-operative patients seeking recovery support.",
  },
  {
    name: "Pre Surgery - Optimization IV Drips",
    slug: "pre-surgery-optimization-drip",
    tagline: "Surgery preparation",
    description: "Prepare your body for surgery with immune support and optimal hydration.",
    benefits: ["Prepares the body for surgery", "Supports immune balance", "Ensures optimal hydration"],
    price: "1200",
    duration: "45-60 min",
    image: "/images/iv-treatments/pre-surgery-optimization.jpg",
    targetAudience: "Patients preparing for elective surgery.",
  },
  {
    name: "Royal Flush Mini IV Drips",
    slug: "royal-flush-mini",
    tagline: "Quick wellness boost",
    description: "A mini version of our popular wellness drip for a quick energy and detox boost.",
    benefits: ["Quick rehydration boost", "Supports energy & detox", "Enhances overall recovery"],
    price: "1100",
    duration: "20-30 min",
    image: "/images/iv-treatments/royal-flush-mini.jpg",
    targetAudience: "Partygoers, travelers, busy individuals needing fast recovery.",
  },
  {
    name: "Myers Cocktail IV Drips",
    slug: "myers-cocktail",
    tagline: "Classic wellness blend",
    description: "The famous Myers Cocktail - a time-tested blend of vitamins and minerals for overall wellness.",
    benefits: ["Classic wellness boost", "Reduces fatigue", "Supports immunity & energy"],
    price: "1100",
    duration: "30-45 min",
    image: "/images/iv-treatments/myers-cocktail.jpg",
    targetAudience: "Clients with chronic fatigue, stress, immune weakness.",
  },
  {
    name: "Vitamin D IV Drips",
    slug: "vitamin-d-drip",
    tagline: "Sunshine vitamin",
    description: "Correct vitamin D deficiency and support bone health with direct IV delivery.",
    benefits: ["Corrects low vitamin D", "Supports bone health", "Enhances immune function"],
    price: "1100",
    duration: "30-45 min",
    image: "/images/iv-treatments/vitamin-d-drip.jpg",
    targetAudience: "Individuals with low vitamin D levels or malabsorption.",
  },
  {
    name: "Super B - B-Complex IV Drips",
    slug: "super-b-complex-drip",
    tagline: "B vitamin boost",
    description: "A comprehensive B-vitamin complex to boost energy and support nervous system health.",
    benefits: ["Boosts natural energy", "Supports nervous-system health", "Helps reduce fatigue"],
    price: "1100",
    duration: "30-45 min",
    image: "/images/iv-treatments/super-b-complex.jpg",
    targetAudience: "Vegans, fatigued clients, those with low B-vitamin intake.",
  },
  {
    name: "Vitamin C + Zinc IV Drips",
    slug: "vitamin-c-zinc-drip",
    tagline: "Immune powerhouse",
    description: "A powerful combination of Vitamin C and Zinc for enhanced immune support.",
    benefits: ["Strengthens immune defense", "Provides antioxidant protection", "Supports recovery"],
    price: "1100",
    duration: "30-45 min",
    image: "/images/iv-treatments/vitamin-c-zinc.jpg",
    targetAudience: "Clients wanting immune support during illness.",
  },
  {
    name: "Vitamin C IV Drips",
    slug: "vitamin-c-drip",
    tagline: "Antioxidant boost",
    description: "High-dose Vitamin C for powerful antioxidant support and immune boosting.",
    benefits: ["High antioxidant support", "Boosts immunity", "Supports collagen production"],
    price: "1100",
    duration: "30-45 min",
    image: "/images/iv-treatments/vitamin-c-drip.jpg",
    targetAudience: "Individuals needing antioxidant or collagen support.",
  },
  {
    name: "Zinc IV Drips",
    slug: "zinc-drip",
    tagline: "Essential mineral",
    description: "Zinc supplementation for immune health, skin maintenance, and reproductive wellness.",
    benefits: ["Supports immune health", "Helps skin & hair maintenance", "Aids reproductive wellness"],
    price: "1050",
    duration: "30-45 min",
    image: "/images/iv-treatments/zinc-drip.jpg",
    targetAudience: "Clients with low zinc, skin issues, or immune weakness.",
  },
  {
    name: "B12 IV Drips",
    slug: "b12-drip",
    tagline: "Energy essential",
    description: "Vitamin B12 supplementation for energy, nerve function, and fatigue reduction.",
    benefits: ["Boosts energy naturally", "Supports nerve function", "Helps improve fatigue"],
    price: "1050",
    duration: "20-30 min",
    image: "/images/iv-treatments/b12-drip.jpg",
    targetAudience: "Vegans, older adults, individuals with B12 deficiency.",
  },
]

export function getIVDripBySlug(slug: string): IVDrip | undefined {
  return ivDripsData.find((drip) => drip.slug === slug)
}

export function getAllIVDripSlugs(): string[] {
  return ivDripsData.map((drip) => drip.slug)
}
